import { boolean, char, integer, json, pgSchema, real, smallint, text, varchar } from 'drizzle-orm/pg-core'

const postgresInformationSchema = pgSchema('information_schema')

export const postgresInformationSchemaTables = postgresInformationSchema.table('tables', {
  table_catalog: text(),
  table_schema: text(),
  table_name: text().notNull(),
  table_type: varchar(),
  self_referencing_column_name: text(),
  reference_generation: varchar(),
  user_defined_type_catalog: text(),
  user_defined_type_schema: text(),
  user_defined_type_name: text(),
  is_insertable_into: varchar(),
  is_typed: varchar(),
  commit_action: varchar(),
})

export const postgresInformationSchemaColumns = postgresInformationSchema.table('columns', {
  table_catalog: text(),
  table_schema: text(),
  table_name: text(),
  column_name: text(),
  ordinal_position: integer(),
  column_default: varchar(),
  is_nullable: varchar(),
  data_type: varchar(),
  character_maximum_length: integer(),
  character_octet_length: integer(),
  numeric_precision: integer(),
  numeric_precision_radix: integer(),
  numeric_scale: integer(),
  datetime_precision: integer(),
  interval_type: varchar(),
  interval_precision: integer(),
  character_set_catalog: text(),
  character_set_schema: text(),
  character_set_name: text(),
  collation_catalog: text(),
  collation_schema: text(),
  collation_name: text(),
  domain_catalog: text(),
  domain_schema: text(),
  domain_name: text(),
  udt_catalog: text(),
  udt_schema: text(),
  udt_name: text(),
  scope_catalog: text(),
  scope_schema: text(),
  scope_name: text(),
  maximum_cardinality: integer(),
  dtd_identifier: text(),
  is_self_referencing: varchar(),
  is_identity: varchar(),
  identity_generation: varchar(),
  identity_start: varchar(),
  identity_increment: varchar(),
  identity_maximum: varchar(),
  identity_minimum: varchar(),
  identity_cycle: varchar(),
  is_generated: varchar(),
  generation_expression: varchar(),
  is_updatable: varchar(),
})

export const postgresPgCatalogPgAm = pgSchema('pg_catalog').table('pg_am', {
  oid: text('oid'),
  amhandler: text('regproc'),
  amtype: text('amtype'),
  amname: text('amname'),
})

export const postgresPgCatalogPgNamespace = pgSchema('pg_catalog').table('pg_namespace', {
  oid: text('oid'),
  nspowner: text('nspowner'),
  nspacl: text('nspacl').array(),
  nspname: text('nspname'),
})

export const postgresPgCatalogPgClass = pgSchema('pg_catalog').table('pg_class', {
  oid: text('oid'),
  relfrozenxid: text('relfrozenxid'),
  relminmxid: text('relminmxid'),
  relacl: text('relacl').array(),
  relnamespace: text('relnamespace'),
  reltype: text('reltype'),
  reloftype: text('reloftype'),
  relowner: text('relowner'),
  relam: text('relam'),
  relfilenode: text('relfilenode'),
  reltablespace: text('reltablespace'),
  relpages: integer('relpages'),
  reltuples: real('reltuples'),
  relallvisible: integer('relallvisible'),
  reltoastrelid: text('reltoastrelid'),
  relhasindex: boolean('relhasindex'),
  relisshared: boolean('relisshared'),
  relpersistence: text('relpersistence'),
  relkind: text('relkind'),
  relnatts: smallint('relnatts'),
  relchecks: smallint('relchecks'),
  relhasrules: boolean('relhasrules'),
  relhastriggers: boolean('relhastriggers'),
  relhassubclass: boolean('relhassubclass'),
  relrowsecurity: boolean('relrowsecurity'),
  relforcerowsecurity: boolean('relforcerowsecurity'),
  relispopulated: boolean('relispopulated'),
  relreplident: text('relreplident'),
  relispartition: boolean('relispartition'),
  relrewrite: text('relrewrite'),
  relname: text('relname'),
  relpartbound: json('relpartbound'),
  reloptions: text('reloptions').array(),
})

export const postgresPgCatalogPgIndex = pgSchema('pg_catalog').table('pg_index', {
  indexrelid: text('indexrelid'),
  indrelid: text('indrelid'),
  indnatts: smallint('indnatts'),
  indnkeyatts: smallint('indnkeyatts'),
  indisunique: boolean('indisunique'),
  indnullsnotdistinct: boolean('indnullsnotdistinct'),
  indisprimary: boolean('indisprimary'),
  indisexclusion: boolean('indisexclusion'),
  indimmediate: boolean('indimmediate'),
  indisclustered: boolean('indisclustered'),
  indisvalid: boolean('indisvalid'),
  indcheckxmin: boolean('indcheckxmin'),
  indisready: boolean('indisready'),
  indislive: boolean('indislive'),
  indisreplident: boolean('indisreplident'),
  indkey: text('indkey').array(),
  indcollation: text('indcollation').array(),
  indclass: text('indclass').array(),
  indoption: text('indoption').array(),
  indexprs: json('indexprs'),
  indpred: json('indpred'),
})

export const postgresPgCatalogPgAttribute = pgSchema('pg_catalog').table('pg_attribute', {
  attrelid: integer('attrelid').notNull().primaryKey(),
  attname: text('attname').notNull().primaryKey(),
  atttypid: integer('atttypid').notNull(),
  attlen: smallint('attlen').notNull(),
  attnum: smallint('attnum').notNull(),
  attcacheoff: integer('attcacheoff').notNull(),
  atttypmod: integer('atttypmod').notNull(),
  attndims: smallint('attndims').notNull(),
  attbyval: boolean('attbyval').notNull(),
  attalign: char('attalign').notNull(),
  attstorage: char('attstorage').notNull(),
  attcompression: char('attcompression').notNull(),
  attnotnull: boolean('attnotnull').notNull(),
  atthasdef: boolean('atthasdef').notNull(),
  atthasmissing: boolean('atthasmissing').notNull(),
  attidentity: char('attidentity').notNull(),
  attgenerated: char('attgenerated').notNull(),
  attisdropped: boolean('attisdropped').notNull(),
  attislocal: boolean('attislocal').notNull(),
  attinhcount: smallint('attinhcount').notNull(),
  attcollation: integer('attcollation').notNull(),
  attstattarget: smallint('attstattarget'),
  attacl: json('attacl'),
  attoptions: text('attoptions').array(),
  attfdwoptions: text('attfdwoptions').array(),
  attmissingval: json('attmissingval'),
})

export const postgresPgCatalogPgType = pgSchema('pg_catalog').table('pg_type', {
  oid: integer('oid').primaryKey(),
  typname: text('typname').notNull(),
  typnamespace: integer('typnamespace').notNull(),
  typowner: integer('typowner').notNull(),
  typlen: smallint('typlen').notNull(),
  typbyval: boolean('typbyval').notNull(),
  typtype: char('typtype').notNull(),
  typcategory: char('typcategory').notNull(),
  typispreferred: boolean('typispreferred').notNull(),
  typisdefined: boolean('typisdefined').notNull(),
  typdelim: char('typdelim').notNull(),
  typrelid: integer('typrelid').notNull(),
  typsubscript: text('typsubscript').notNull(),
  typelem: integer('typelem').notNull(),
  typarray: integer('typarray').notNull(),
  typinput: text('typinput').notNull(),
  typoutput: text('typoutput').notNull(),
  typreceive: text('typreceive').notNull(),
  typsend: text('typsend').notNull(),
  typmodin: text('typmodin').notNull(),
  typmodout: text('typmodout').notNull(),
  typanalyze: text('typanalyze').notNull(),
  typalign: char('typalign').notNull(),
  typstorage: char('typstorage').notNull(),
  typnotnull: boolean('typnotnull').notNull(),
  typbasetype: integer('typbasetype').notNull(),
  typtypmod: integer('typtypmod').notNull(),
  typndims: integer('typndims').notNull(),
  typcollation: integer('typcollation').notNull(),
  typdefaultbin: json('typdefaultbin'),
  typdefault: text('typdefault'),
  typacl: text('typacl').array(),
})
