name: CI

on:
  push:
    paths:
      - airi-minecraft/**
      - .github/workflows/airi-minecraft-ci.yml
    branches:
      - main

  pull_request:
    paths:
      - airi-minecraft/**
      - .github/workflows/airi-minecraft-ci.yml
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

          cache-dependency-path: airi-minecraft/pnpm-lock.yaml
      - name: Install
        run: pnpm install
        working-directory: airi-minecraft

      - name: Lint
        run: pnpm run lint
        working-directory: airi-minecraft

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

          cache-dependency-path: airi-minecraft/pnpm-lock.yaml
      - name: Install
        run: pnpm install
        working-directory: airi-minecraft

      - name: Typecheck
        run: pnpm run typecheck
        working-directory: airi-minecraft
