name: CI

on:
  push:
    paths:
      - airi-factorio/**
      - .github/workflows/airi-factorio-ci.yml
    branches:
      - main

  pull_request:
    paths:
      - airi-factorio/**
      - .github/workflows/airi-factorio-ci.yml
    branches:
      - main

jobs:
  lint-typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

          cache-dependency-path: airi-factorio/pnpm-lock.yaml
      - name: Install
        run: pnpm install
          working-directory: airi-factorio

      - name: Lint
        run: pnpm run lint
          working-directory: airi-factorio

  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.9.1
        with:
          cache: true

      - name: Lint
        run: pixi run lint
          working-directory: airi-factorio

  typecheck-typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

          cache-dependency-path: airi-factorio/pnpm-lock.yaml
      - name: Install
        run: pnpm install
          working-directory: airi-factorio

      - name: Typecheck
        run: pnpm run build && pnpm run typecheck
          working-directory: airi-factorio

  typecheck-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.9.1
        with:
          cache: true

      - name: Typecheck
        run: pixi run typecheck
          working-directory: airi-factorio
