name: HuggingFace Spaces

on:
  push:
    paths:
      - airi-factorio/**
      - .github/workflows/airi-factorio-deploy-hf-space.yml
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - run: |-
        working-directory: airi-factorio
          git clone https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/proj-airi/factorio-yolo-v0-playground --depth 1 apps/factorio-yolo-v0-playground/dist
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ secrets.HF_USERNAME }}

      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

          cache-dependency-path: airi-factorio/pnpm-lock.yaml
      - run: pnpm install
        working-directory: airi-factorio
      - run: pnpm build
        working-directory: airi-factorio

      - id: airi_diff
        working-directory: ./apps/factorio-yolo-v0-playground/dist
        run: |-
          working-directory: airi-factorio
          git lfs ls-files --all
          git add .
          if [[ -n $(git status --porcelain) ]]; then
              echo "changes=true" >> "$GITHUB_OUTPUT";
          fi

      - if: steps.airi_diff.outputs.changes == 'true'
        working-directory: ./apps/factorio-yolo-v0-playground/dist
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
        run: |-
          working-directory: airi-factorio
          git config --local user.email "self@lemonneko.moe"
          git config --local user.name "LemonNeko"
          git commit -m "release: build ${{ github.sha }}"
          git lfs push origin main --all
          git push -f
