name: CI

on:
  push:
    paths:
      - unspeech/**
      - .github/workflows/unspeech-ci.yaml
    branches:
      - main
  pull_request:
    paths:
      - unspeech/**
      - .github/workflows/unspeech-ci.yaml
    branches:
      - main

jobs:
  build-test:
    name: Build Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true

      - name: Test Build
        run: go build ./...
          working-directory: unspeech

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          # Optional: golangci-lint command line arguments.
          args: --timeout=10m

  unittest:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache-dependency-path: unspeech/go.sum

      - name: Unit tests
        run: |
          working-directory: unspeech
          go test ./... -coverprofile=coverage.out -covermode=atomic -p=1
          go tool cover -func coverage.out
