name: check

on:
  pull_request:
    paths:
      - xsai-use/**
      - .github/workflows/xsai-use-check.yml
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: latest
          registry-url: https://registry.npmjs.org
          cache-dependency-path: xsai-use/pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile
        working-directory: xsai-use
      - run: pnpm -r build
        working-directory: xsai-use
      - run: pnpm lint
        working-directory: xsai-use
