name: check

on:
  pull_request:
    paths:
      - xsmcp/**
      - .github/workflows/xsmcp-check.yml
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: latest
          registry-url: https://registry.npmjs.org
          cache-dependency-path: xsmcp/pnpm-lock.yaml
      - run: pnpm i
        working-directory: xsmcp
      - run: pnpm -r build
        working-directory: xsmcp
      - run: pnpm lint
        working-directory: xsmcp
      - run: pnpm test
        working-directory: xsmcp
